#!/usr/bin/env python3
import json
import os
import urllib.request
from collections import Counter

OWNER = os.environ.get("GITHUB_REPOSITORY_OWNER", "Skbindas")
TOKEN = os.environ.get("GITHUB_TOKEN", "")

def gh_json(url):
    req = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {TOKEN}" if TOKEN else "",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "Skbindas-profile-stats",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)

def fetch_all(url):
    out = []
    page = 1
    while True:
        sep = "&" if "?" in url else "?"
        batch = gh_json(f"{url}{sep}per_page=100&page={page}")
        if not batch:
            break
        out.extend(batch)
        if len(batch) < 100:
            break
        page += 1
    return out

def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))

def card(title, items, width=900, height=260):
    rows = []
    y = 110
    for label, value in items:
        rows.append(
            f'<text x="65" y="{y}" fill="#6B7280" font-family="Arial, Helvetica, sans-serif" font-size="16">{esc(label)}</text>'
            f'<text x="{width-65}" y="{y}" text-anchor="end" fill="#111827" font-family="Arial, Helvetica, sans-serif" font-size="20" font-weight="700">{esc(value)}</text>'
        )
        y += 42
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#EFF6FF"/><stop offset="1" stop-color="#F5F3FF"/></linearGradient></defs>
<rect x="2" y="2" width="{width-4}" height="{height-4}" rx="22" fill="white" stroke="#E5E7EB"/>
<rect x="3" y="3" width="7" height="{height-6}" rx="4" fill="url(#g)"/>
<text x="65" y="62" fill="#111827" font-family="Arial, Helvetica, sans-serif" font-size="24" font-weight="700">{esc(title)}</text>
<line x1="65" y1="82" x2="{width-65}" y2="82" stroke="#E5E7EB"/>
{''.join(rows)}
<text x="65" y="{height-22}" fill="#9CA3AF" font-family="Arial, Helvetica, sans-serif" font-size="12">Auto-generated from GitHub public repository data</text>
</svg>'''

def lang_card(counter, width=900, height=360):
    total = sum(counter.values()) or 1
    colors = ["#2563EB","#06B6D4","#7C3AED","#16A34A","#EA580C","#DB2777","#4F46E5","#0891B2"]
    rows = []
    y = 106
    for i, (lang, count) in enumerate(counter.most_common(8)):
        pct = count / total * 100
        bar = max(18, int(520 * pct / 100))
        c = colors[i % len(colors)]
        rows.append(
            f'<text x="65" y="{y}" fill="#374151" font-family="Arial, Helvetica, sans-serif" font-size="15" font-weight="600">{esc(lang)}</text>'
            f'<rect x="205" y="{y-14}" width="520" height="12" rx="6" fill="#EEF2FF"/>'
            f'<rect x="205" y="{y-14}" width="{bar}" height="12" rx="6" fill="{c}"/>'
            f'<text x="760" y="{y}" fill="#6B7280" font-family="Arial, Helvetica, sans-serif" font-size="14">{pct:.1f}%</text>'
        )
        y += 31
    if not rows:
        rows.append('<text x="65" y="120" fill="#6B7280" font-family="Arial, Helvetica, sans-serif" font-size="16">No language data available yet.</text>')
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
<rect x="2" y="2" width="{width-4}" height="{height-4}" rx="22" fill="white" stroke="#E5E7EB"/>
<text x="65" y="62" fill="#111827" font-family="Arial, Helvetica, sans-serif" font-size="24" font-weight="700">Top Languages</text>
<text x="65" y="84" fill="#9CA3AF" font-family="Arial, Helvetica, sans-serif" font-size="12">Based on code size in public, non-fork repositories</text>
{''.join(rows)}
<text x="65" y="{height-18}" fill="#9CA3AF" font-family="Arial, Helvetica, sans-serif" font-size="12">Auto-generated by GitHub Actions • @{esc(OWNER)}</text>
</svg>'''

user = gh_json(f"https://api.github.com/users/{OWNER}")
repos = fetch_all(f"https://api.github.com/users/{OWNER}/repos?type=owner&sort=updated")

public_repos = [r for r in repos if not r.get("private")]
original_public = [r for r in public_repos if not r.get("fork")]
stars = sum(int(r.get("stargazers_count", 0)) for r in public_repos)
forks = sum(int(r.get("forks_count", 0)) for r in public_repos)

languages = Counter()
for r in original_public:
    try:
        data = gh_json(r["languages_url"])
        languages.update({k: int(v) for k, v in data.items()})
    except Exception:
        pass

os.makedirs("assets", exist_ok=True)
with open("assets/github-stats.svg", "w", encoding="utf-8") as f:
    f.write(card("GitHub Activity", [
        ("Public repositories", len(public_repos)),
        ("Original public repositories", len(original_public)),
        ("Stars across public repos", stars),
        ("Forks across public repos", forks),
        ("Followers", int(user.get("followers", 0))),
    ], height=300))

with open("assets/top-languages.svg", "w", encoding="utf-8") as f:
    f.write(lang_card(languages))
